apiVersion: v1
kind: Pod
metadata:
  name: edge-data-collector
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-data-processing
    stage: collection
  annotations:
    data.scheduler.thesis/input-1: "edge-data/sensor-readings.json,419430400,10,9,json"
    data.scheduler.thesis/output-1: "intermediate/preprocessed-readings.json,209715200,0,8,json"
    scheduler.thesis/prefer-edge: "true"
    scheduler.thesis/prefer-region: "region-1"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
    - name: edge-collector
      image: davidandw190/workload-sim:latest
      command: [ "python", "/app/simulator.py" ]
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKLOAD_TYPE
          value: "edge-collection"
        - name: WORKLOAD_ACTION
          value: "collect"
        - name: WORKLOAD_INTENSITY
          value: "high"
      resources:
        requests:
          memory: "512Mi"
          cpu: "400m"
        limits:
          memory: "1Gi"
          cpu: "800m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: region1-processor
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-data-processing
    stage: processing
  annotations:
    data.scheduler.thesis/input-1: "intermediate/preprocessed-readings.json,52428800,15,7,json"
    data.scheduler.thesis/input-2: "region1-bucket/reference-data.json,104857600,5,6,json"
    data.scheduler.thesis/output-1: "region1-bucket/processed-data.json,26214400,0,8,json"
    scheduler.thesis/prefer-region: "region-1"
    scheduler.thesis/prefer-edge: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
    - name: region-processor
      image: davidandw190/workload-sim:latest
      command: [ "python", "/app/simulator.py" ]
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKLOAD_TYPE
          value: "data-processing"
        - name: WORKLOAD_ACTION
          value: "process"
        - name: WORKLOAD_INTENSITY
          value: "high"
      resources:
        requests:
          memory: "768Mi"
          cpu: "600m"
        limits:
          memory: "1.5Gi"
          cpu: "1.2"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: region2-processor
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-data-processing
    stage: processing
  annotations:
    data.scheduler.thesis/input-1: "intermediate/preprocessed-readings.json,52428800,15,7,json"
    data.scheduler.thesis/input-2: "region2-bucket/reference-data.json,104857600,5,6,json"
    data.scheduler.thesis/output-1: "region2-bucket/processed-data.json,26214400,0,8,json"
    scheduler.thesis/prefer-region: "region-2"
    scheduler.thesis/prefer-edge: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
    - name: region-processor
      image: davidandw190/workload-sim:latest
      command: [ "python", "/app/simulator.py" ]
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKLOAD_TYPE
          value: "data-processing"
        - name: WORKLOAD_ACTION
          value: "process"
        - name: WORKLOAD_INTENSITY
          value: "high"
      resources:
        requests:
          memory: "768Mi"
          cpu: "600m"
        limits:
          memory: "1.5Gi"
          cpu: "1.2"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: central-aggregator
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-data-processing
    stage: aggregation
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/processed-data.json,26214400,5,8,json"
    data.scheduler.thesis/input-2: "region2-bucket/processed-data.json,26214400,5,8,json"
    data.scheduler.thesis/output-1: "results/aggregated-results.json,15728640,0,7,json"
    scheduler.thesis/prefer-cloud: "true"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
    - name: aggregator
      image: davidandw190/workload-sim:latest
      command: [ "python", "/app/simulator.py" ]
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKLOAD_TYPE
          value: "data-aggregation"
        - name: WORKLOAD_ACTION
          value: "analyze"
        - name: WORKLOAD_INTENSITY
          value: "high"
      resources:
        requests:
          memory: "1Gi"
          cpu: "800m"
        limits:
          memory: "2Gi"
          cpu: "1.5"
  restartPolicy: Never