# benchmarks/simulated/workloads/data-intensive-analytics.yaml (new workload)
apiVersion: v1
kind: Pod
metadata:
  name: data-collector-region1
  namespace: scheduler-benchmark
  labels:
    workload: data-intensive-analytics
    stage: collection
  annotations:
    data.scheduler.thesis/input-1: "edge-data/sensor-logs.json,209715200,10,9,json"
    data.scheduler.thesis/output-1: "intermediate/region1-collected.parquet,104857600,0,8,parquet"
    scheduler.thesis/prefer-region: "region-1"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: region1-collector
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "region-collection"
    - name: WORKLOAD_ACTION
      value: "collect"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "512Mi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "800m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: data-collector-region2
  namespace: scheduler-benchmark
  labels:
    workload: data-intensive-analytics
    stage: collection
  annotations:
    data.scheduler.thesis/input-1: "region2-bucket/iot-readings.json,209715200,10,9,json"
    data.scheduler.thesis/output-1: "intermediate/region2-collected.parquet,104857600,0,8,parquet"
    scheduler.thesis/prefer-region: "region-2"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: region2-collector
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "region-collection"
    - name: WORKLOAD_ACTION
      value: "collect"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "512Mi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "800m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: feature-extractor
  namespace: scheduler-benchmark
  labels:
    workload: data-intensive-analytics
    stage: processing
  annotations:
    data.scheduler.thesis/input-1: "intermediate/region1-collected.parquet,104857600,15,8,parquet"
    data.scheduler.thesis/input-2: "intermediate/region2-collected.parquet,104857600,15,8,parquet"
    data.scheduler.thesis/output-1: "intermediate/feature-data.parquet,52428800,0,7,parquet"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/prefer-cloud: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: feature-processor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "feature-extraction"
    - name: WORKLOAD_ACTION
      value: "process"
    - name: WORKLOAD_INTENSITY
      value: "very-high"
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: model-trainer
  namespace: scheduler-benchmark
  labels:
    workload: data-intensive-analytics
    stage: training
  annotations:
    data.scheduler.thesis/input-1: "intermediate/feature-data.parquet,52428800,30,7,parquet"
    data.scheduler.thesis/output-1: "results/model.h5,262144000,0,9,h5"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/memory-intensive: "true"
    scheduler.thesis/prefer-cloud: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: model-trainer
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "model-training"
    - name: WORKLOAD_ACTION
      value: "train"
    - name: WORKLOAD_INTENSITY
      value: "very-high"
    resources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: edge-inference-region1
  namespace: scheduler-benchmark
  labels:
    workload: data-intensive-analytics
    stage: inference
  annotations:
    data.scheduler.thesis/input-1: "results/model.h5,262144000,5,9,h5"
    data.scheduler.thesis/input-2: "edge-data/live-data.json,10485760,2,8,json"
    data.scheduler.thesis/output-1: "edge-data/predictions-region1.json,5242880,0,7,json"
    scheduler.thesis/prefer-region: "region-1"
    scheduler.thesis/prefer-edge: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: edge-inference
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "inference"
    - name: WORKLOAD_ACTION
      value: "predict"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    resources:
      requests:
        memory: "512Mi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "800m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: edge-inference-region2
  namespace: scheduler-benchmark
  labels:
    workload: data-intensive-analytics
    stage: inference
  annotations:
    data.scheduler.thesis/input-1: "results/model.h5,262144000,5,9,h5"
    data.scheduler.thesis/input-2: "region2-bucket/live-data.json,10485760,2,8,json"
    data.scheduler.thesis/output-1: "region2-bucket/predictions-region2.json,5242880,0,7,json"
    scheduler.thesis/prefer-region: "region-2"
    scheduler.thesis/prefer-edge: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: edge-inference
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "inference"
    - name: WORKLOAD_ACTION
      value: "predict"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    resources:
      requests:
        memory: "512Mi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "800m"
  restartPolicy: Never
