apiVersion: v1
kind: Pod
metadata:
  name: edge-data-collector
  namespace: scheduler-benchmark
  labels:
    workload: edge-to-cloud-pipeline
    stage: collect
  annotations:
    data.scheduler.thesis/input-1: "edge-data/sensor-data.json,20971520,5,9,json"
    data.scheduler.thesis/output-1: "intermediate/preprocessed-data.json,10485760,0,8,json"
    scheduler.thesis/prefer-edge: "true"
    scheduler.thesis/prefer-region: "region-1"
    scheduler.thesis/data-intensive: "true"
    scheduler.thesis/low-latency: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
    - name: edge-collector
      image: davidandw190/workload-sim:latest
      command: [ "python", "/app/simulator.py" ]
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKLOAD_TYPE
          value: "edge-collection"
        - name: WORKLOAD_ACTION
          value: "collect"
        - name: WORKLOAD_INTENSITY
          value: "medium"
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "400m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: cloud-data-processor
  namespace: scheduler-benchmark
  labels:
    workload: edge-to-cloud-pipeline
    stage: process
  annotations:
    data.scheduler.thesis/input-1: "intermediate/preprocessed-data.json,10485760,10,8,json"
    data.scheduler.thesis/output-1: "results/processed-results.json,5242880,0,7,json"
    scheduler.thesis/prefer-cloud: "true"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/memory-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
    - name: cloud-processor
      image: davidandw190/workload-sim:latest
      command: [ "python", "/app/simulator.py" ]
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKLOAD_TYPE
          value: "cloud-processing"
        - name: WORKLOAD_ACTION
          value: "process"
        - name: WORKLOAD_INTENSITY
          value: "high"
      resources:
        requests:
          memory: "1Gi"
          cpu: "800m"
        limits:
          memory: "2Gi"
          cpu: "1.5"
  restartPolicy: Never