# mixed-compute-data-workload.yaml
apiVersion: v1
kind: Pod
metadata:
  name: data-extract-light
  namespace: scheduler-benchmark
  labels:
    workload: mixed-compute-data-workload
    stage: extraction
  annotations:
    data.scheduler.thesis/input-1: "edge-data/raw-data.json,104857600,5,8,json"
    data.scheduler.thesis/output-1: "intermediate/extracted-data-1.json,52428800,0,7,json"
    scheduler.thesis/data-intensive: "true"
    scheduler.thesis/prefer-edge: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-extractor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-extraction"
    - name: WORKLOAD_ACTION
      value: "extract"
    - name: WORKLOAD_INTENSITY
      value: "low"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: compute-transform-heavy
  namespace: scheduler-benchmark
  labels:
    workload: mixed-compute-data-workload
    stage: transformation
  annotations:
    data.scheduler.thesis/input-1: "intermediate/extracted-data-1.json,52428800,30,7,json"
    data.scheduler.thesis/output-1: "intermediate/transformed-data-1.json,26214400,0,6,json"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/prefer-cloud: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-transformer
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-transformation"
    - name: WORKLOAD_ACTION
      value: "transform"
    - name: WORKLOAD_INTENSITY
      value: "very-high"
    resources:
      requests:
        memory: "2Gi"
        cpu: "1.5"
      limits:
        memory: "4Gi"
        cpu: "3"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: data-extract-heavy
  namespace: scheduler-benchmark
  labels:
    workload: mixed-compute-data-workload
    stage: extraction
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/large-dataset.json,1073741824,8,9,json"
    data.scheduler.thesis/output-1: "intermediate/extracted-data-2.json,536870912,0,8,json"
    scheduler.thesis/data-intensive: "true"
    scheduler.thesis/prefer-region: "region-1"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-extractor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-extraction"
    - name: WORKLOAD_ACTION
      value: "extract"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "1Gi"
        cpu: "800m"
      limits:
        memory: "2Gi"
        cpu: "1.5"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: compute-transform-light
  namespace: scheduler-benchmark
  labels:
    workload: mixed-compute-data-workload
    stage: transformation
  annotations:
    data.scheduler.thesis/input-1: "intermediate/extracted-data-2.json,536870912,10,8,json"
    data.scheduler.thesis/output-1: "intermediate/transformed-data-2.json,268435456,0,7,json"
    scheduler.thesis/compute-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-transformer
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-transformation"
    - name: WORKLOAD_ACTION
      value: "transform"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    resources:
      requests:
        memory: "768Mi"
        cpu: "500m"
      limits:
        memory: "1.5Gi"
        cpu: "1"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: balanced-merger
  namespace: scheduler-benchmark
  labels:
    workload: mixed-compute-data-workload
    stage: merging
  annotations:
    data.scheduler.thesis/input-1: "intermediate/transformed-data-1.json,26214400,5,6,json"
    data.scheduler.thesis/input-2: "intermediate/transformed-data-2.json,268435456,5,7,json"
    data.scheduler.thesis/output-1: "intermediate/merged-data.json,294912000,0,7,json"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-merger
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-merging"
    - name: WORKLOAD_ACTION
      value: "merge"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "1Gi"
        cpu: "800m"
      limits:
        memory: "2Gi"
        cpu: "1.5"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: data-aggregator-heavy
  namespace: scheduler-benchmark
  labels:
    workload: mixed-compute-data-workload
    stage: aggregation
  annotations:
    data.scheduler.thesis/input-1: "intermediate/merged-data.json,294912000,10,7,json"
    data.scheduler.thesis/output-1: "results/aggregated-results.json,104857600,0,8,json"
    data.scheduler.thesis/output-2: "region1-bucket/region1-results.json,52428800,0,9,json"
    data.scheduler.thesis/output-3: "region2-bucket/region2-results.json,52428800,0,9,json"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-aggregator
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-aggregation"
    - name: WORKLOAD_ACTION
      value: "aggregate"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
  restartPolicy: Never
