apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-locality-scheduler
  namespace: data-locality-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-locality-scheduler-role
rules:
- apiGroups: [ "" ]
  resources: [ "endpoints" ]
  verbs: [ "get", "create", "update" ]
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "bindings", "pods/binding" ]
  verbs: [ "create" ]
- apiGroups: [ "" ]
  resources: [ "pods/status" ]
  verbs: [ "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch", "update" ]
- apiGroups: [ "" ]
  resources: [ "persistentvolumes", "persistentvolumeclaims" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "services" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "storage.k8s.io" ]
  resources: [ "storageclasses" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-locality-scheduler-binding
subjects:
- kind: ServiceAccount
  name: data-locality-scheduler
  namespace: data-locality-scheduler
roleRef:
  kind: ClusterRole
  name: data-locality-scheduler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-daemon
  namespace: data-locality-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-capability-daemon-role
rules:
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch" ]
- apiGroups: [ "" ]
  resources: [ "persistentvolumes", "persistentvolumeclaims" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-capability-daemon-binding
subjects:
- kind: ServiceAccount
  name: node-daemon
  namespace: data-locality-scheduler
roleRef:
  kind: ClusterRole
  name: node-capability-daemon-role
  apiGroup: rbac.authorization.k8s.io
