apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-region-test
  namespace: data-locality-scheduler
data:
  test.py: |
    import time
    import os

    print("Starting cross-region data processing test...")
    print(f"Running on node: {os.environ.get('NODE_NAME', 'unknown')}")
    print(f"Region: {os.environ.get('NODE_REGION', 'unknown')}")
    print(f"Zone: {os.environ.get('NODE_ZONE', 'unknown')}")

    # Simulate processing
    time.sleep(3600)
---
apiVersion: v1
kind: Pod
metadata:
  name: region1-to-region2-transfer
  namespace: data-locality-scheduler
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/large-data.json,104857600,10,5,json"
    data.scheduler.thesis/output-1: "region2-bucket/processed-data.json,52428800,0,3,json"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: transfer-processor
    image: python:3.9
    command: [ "python", "/tests/test.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: NODE_REGION
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: NODE_ZONE
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - name: tests
      mountPath: /tests
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  volumes:
  - name: tests
    configMap:
      name: cross-region-test
  restartPolicy: Never
