apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: region1-processor
  namespace: data-locality-scheduler
  annotations:
    scheduler.knative.dev/scheduler-name: "data-locality-scheduler"
    scheduler.thesis/data-intensive: "true"
    data.scheduler.thesis/input-1: "region1-specific-data/test-file.txt,1024000000,30"
    scheduler.thesis/prefer-region: "region-1"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go:latest
        ports:
        - containerPort: 8080
        env:
        - name: TARGET
          value: "Region 1 Data Processor"
