apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-data-processor
  namespace: eo-workflow
  annotations:
    # static service-level data dependencies
    data.scheduler.thesis/input-1: "test-bucket/input.dat,1048576,10,5,test"
    scheduler.thesis/data-intensive: "true"
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go:latest
        ports:
        - containerPort: 8080
        env:
        - name: TARGET
          value: "Data Processing Service"
