apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-locality-webhook
  namespace: data-locality-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-locality-webhook
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "serving.knative.dev" ]
  resources: [ "services", "revisions", "configurations" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-locality-webhook
subjects:
- kind: ServiceAccount
  name: data-locality-webhook
  namespace: data-locality-scheduler
roleRef:
  kind: ClusterRole
  name: data-locality-webhook
  apiGroup: rbac.authorization.k8s.io
