name: "Data Locality Scheduler Benchmark"
version: "0.5.2"

kubernetes:
  namespace: "scheduler-benchmark"
  setup_storage: true
  storage_providers:
  - name: "minio-central"
    type: "object"
    region: "central"
  - name: "minio-edge-region1"
    type: "object"
    region: "region-1"
  - name: "minio-edge-region2"
    type: "object"
    region: "region-2"

schedulers:
- name: "data-locality-scheduler"
  description: "Data locality aware scheduler"
  config:
    dataLocalityWeight: 0.6
    nodeTypeWeight: 0.2
    resourceWeight: 0.1
    nodeAffinityWeight: 0.1
- name: "default-scheduler"
  description: "Kubernetes default scheduler"

workloads:
- name: "ml-training-pipeline"
  description: "Machine learning training pipeline with data collection, feature extraction, model training, and inference"
  iterations: 3
  data_intensity: "high"
  compute_intensity: "high"
  max_wait_time: 600
- name: "cross-region-data-processing"
  description: "Cross-region data processing with region-specific handling"
  iterations: 3
  data_intensity: "high"
  compute_intensity: "medium"
  max_wait_time: 600
# - name: "edge-to-cloud-pipeline"
#   description: "IoT data processing pipeline from edge to cloud"
#   iterations: 1
#   data_intensity: "high"
#   compute_intensity: "medium"
#   max_wait_time: 600

# - name: "cross-region-analytics"
#   description: "Analytics workload using data from multiple regions"
#   iterations: 1
#   data_intensity: "high"
#   compute_intensity: "high"
#   max_wait_time: 300 # 5 minutes

metrics:
  collect_node_metrics: true
  collect_pod_metrics: true
  collect_network_metrics: true
  data_transfer_metrics: true
  bandwidth_utilization: true
  collection_interval: 5 # seconds
  latency_tracking: true
  detailed_data_locality: true
  cross_region_transfer_tracking: true

execution:
  max_wait_time: 300
  pod_timeout: 300
  poll_interval: 3
  parallel_runs: false
  cleanup_after_run: true
  validation_level: "thorough"
  detailed_logs: true
  simulation_duration: 30
