apiVersion: v1
kind: Pod
metadata:
  name: edge-stream-ingestion
  namespace: scheduler-benchmark
  labels:
    workload: stream-processing-pipeline
    stage: ingestion
  annotations:
    data.scheduler.thesis/output-1: "edge-data/stream-buffer-1.dat,52428800"
    data.scheduler.thesis/output-2: "edge-data/stream-buffer-2.dat,52428800"
    scheduler.thesis/prefer-edge: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: stream-ingestion
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "stream-ingestion"
    - name: WORKLOAD_ACTION
      value: "collect"
    - name: WORKLOAD_INTENSITY
      value: "high"
    - name: WORKLOAD_DURATION
      value: "45"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: stream-processor-1
  namespace: scheduler-benchmark
  labels:
    workload: stream-processing-pipeline
    stage: processing
  annotations:
    data.scheduler.thesis/input-1: "edge-data/stream-buffer-1.dat,52428800"
    data.scheduler.thesis/output-1: "intermediate/processed-stream-1.dat,26214400"
    scheduler.thesis/compute-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: stream-processor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "stream-processing"
    - name: WORKLOAD_ACTION
      value: "transform"
    - name: WORKLOAD_INTENSITY
      value: "very-high"
    - name: WORKLOAD_DURATION
      value: "60"
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: stream-processor-2
  namespace: scheduler-benchmark
  labels:
    workload: stream-processing-pipeline
    stage: processing
  annotations:
    data.scheduler.thesis/input-1: "edge-data/stream-buffer-2.dat,52428800"
    data.scheduler.thesis/output-1: "intermediate/processed-stream-2.dat,26214400"
    scheduler.thesis/compute-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: stream-processor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "stream-processing"
    - name: WORKLOAD_ACTION
      value: "transform"
    - name: WORKLOAD_INTENSITY
      value: "very-high"
    - name: WORKLOAD_DURATION
      value: "60"
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: stream-aggregator
  namespace: scheduler-benchmark
  labels:
    workload: stream-processing-pipeline
    stage: aggregation
  annotations:
    data.scheduler.thesis/input-1: "intermediate/processed-stream-1.dat,26214400"
    data.scheduler.thesis/input-2: "intermediate/processed-stream-2.dat,26214400"
    data.scheduler.thesis/output-1: "results/stream-analytics.json,10485760"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: stream-aggregator
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "stream-aggregation"
    - name: WORKLOAD_ACTION
      value: "analyze"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    - name: WORKLOAD_DURATION
      value: "40"
    resources:
      requests:
        memory: "512Mi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "800m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: stream-sink
  namespace: scheduler-benchmark
  labels:
    workload: stream-processing-pipeline
    stage: output
  annotations:
    data.scheduler.thesis/input-1: "results/stream-analytics.json,10485760"
    data.scheduler.thesis/output-1: "edge-data/stream-output.json,5242880"
    data.scheduler.thesis/output-2: "datasets/stream-archive.json,10485760"
    scheduler.thesis/prefer-edge: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: stream-sink
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "stream-sink"
    - name: WORKLOAD_ACTION
      value: "store"
    - name: WORKLOAD_INTENSITY
      value: "low"
    - name: WORKLOAD_DURATION
      value: "30"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  restartPolicy: Never
