# benchmarks/workloads/cross-region-analytics.yaml
apiVersion: v1
kind: Pod
metadata:
  name: region1-data-extractor
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-analytics
    component: region1-extractor
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/region1-data.json,1048576,15,8,json"
    data.scheduler.thesis/output-1: "intermediate/region1-extracted.json,5242880,0,6,json"
    scheduler.thesis/prefer-region: "region-1"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: region1-extractor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-extraction"
    - name: WORKLOAD_ACTION
      value: "extract"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    - name: DATA_SCHEDULER_THESIS_INPUT_1
      value: "region1-bucket/region1-data.json,10485760,15,8,json"
    - name: DATA_SCHEDULER_THESIS_OUTPUT_1
      value: "intermediate/region1-extracted.json,5242880,0,6,json"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: region2-data-extractor
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-analytics
    component: region2-extractor
  annotations:
    data.scheduler.thesis/input-1: "region2-bucket/region2-data.json,10485760,15,8,json"
    data.scheduler.thesis/output-1: "intermediate/region2-extracted.json,5242880,0,6,json"
    scheduler.thesis/prefer-region: "region-2"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: region2-extractor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-extraction"
    - name: WORKLOAD_ACTION
      value: "extract"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    - name: DATA_SCHEDULER_THESIS_INPUT_1
      value: "region2-bucket/region2-data.json,10485760,15,8,json"
    - name: DATA_SCHEDULER_THESIS_OUTPUT_1
      value: "intermediate/region2-extracted.json,5242880,0,6,json"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: data-aggregator
  namespace: scheduler-benchmark
  labels:
    workload: cross-region-analytics
    component: aggregator
  annotations:
    data.scheduler.thesis/input-1: "intermediate/region1-extracted.json,5242880,10,7,json"
    data.scheduler.thesis/input-2: "intermediate/region2-extracted.json,5242880,10,7,json"
    data.scheduler.thesis/output-1: "results/aggregated-analysis.json,1048576,0,5,json"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/prefer-cloud: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: aggregator
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-aggregation"
    - name: WORKLOAD_ACTION
      value: "analyze"
    - name: WORKLOAD_INTENSITY
      value: "high"
    - name: DATA_SCHEDULER_THESIS_INPUT_1
      value: "intermediate/region1-extracted.json,5242880,10,7,json"
    - name: DATA_SCHEDULER_THESIS_INPUT_2
      value: "intermediate/region2-extracted.json,5242880,10,7,json"
    - name: DATA_SCHEDULER_THESIS_OUTPUT_1
      value: "results/aggregated-analysis.json,1048576,0,5,json"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
  restartPolicy: Never
