apiVersion: v1
kind: Pod
metadata:
  name: region1-data-processor
  namespace: scheduler-benchmark
  labels:
    workload: data-locality-test
    test: region1-data
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/test-region1.dat,10485760,10,8,binary"
    data.scheduler.thesis/output-1: "intermediate/region1-output.dat,5242880,0,5,binary"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: region1-processor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: WORKLOAD_TYPE
      value: "data-intensive"
    - name: WORKLOAD_ACTION
      value: "process"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
---
apiVersion: v1
kind: Pod
metadata:
  name: region2-data-processor
  namespace: scheduler-benchmark
  labels:
    workload: data-locality-test
    test: region2-data
  annotations:
    data.scheduler.thesis/input-1: "region2-bucket/test-region2.dat,10485760,10,8,binary"
    data.scheduler.thesis/output-1: "intermediate/region2-output.dat,5242880,0,5,binary"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: region2-processor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: WORKLOAD_TYPE
      value: "data-intensive"
    - name: WORKLOAD_ACTION
      value: "process"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
---
apiVersion: v1
kind: Pod
metadata:
  name: central-data-processor
  namespace: scheduler-benchmark
  labels:
    workload: data-locality-test
    test: central-data
  annotations:
    data.scheduler.thesis/input-1: "datasets/test-central.dat,10485760,10,8,binary"
    data.scheduler.thesis/output-1: "intermediate/central-output.dat,5242880,0,5,binary"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: central-processor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: WORKLOAD_TYPE
      value: "data-intensive"
    - name: WORKLOAD_ACTION
      value: "process"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
