apiVersion: v1
kind: Pod
metadata:
  name: edge-data-collector
  namespace: scheduler-benchmark
  labels:
    workload: ml-training-pipeline
    stage: data-collection
  annotations:
    data.scheduler.thesis/input-1: "edge-data/sensor-data-training.json,52428800,5,8,json"
    data.scheduler.thesis/output-1: "intermediate/collected-data.parquet,26214400,0,7,parquet"
    scheduler.thesis/prefer-edge: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-collector
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "data-collection"
    - name: WORKLOAD_ACTION
      value: "collect"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "256Mi"
        cpu: "300m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: feature-extraction
  namespace: scheduler-benchmark
  labels:
    workload: ml-training-pipeline
    stage: feature-extraction
  annotations:
    data.scheduler.thesis/input-1: "intermediate/collected-data.parquet,26214400,15,7,parquet"
    data.scheduler.thesis/output-1: "intermediate/features.npz,15728640,0,7,npz"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/data-intensive: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: feature-extractor
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "feature-extraction"
    - name: WORKLOAD_ACTION
      value: "transform"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "1Gi"
        cpu: "800m"
      limits:
        memory: "2Gi"
        cpu: "1.5"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: model-training
  namespace: scheduler-benchmark
  labels:
    workload: ml-training-pipeline
    stage: training
  annotations:
    data.scheduler.thesis/input-1: "intermediate/features.npz,15728640,30,8,npz"
    data.scheduler.thesis/input-2: "region1-bucket/reference-models.h5,52428800,10,7,h5"
    data.scheduler.thesis/output-1: "region1-bucket/trained-model.h5,209715200,0,9,h5"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/prefer-cloud: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: model-trainer
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "model-training"
    - name: WORKLOAD_ACTION
      value: "train"
    - name: WORKLOAD_INTENSITY
      value: "very-high"
    resources:
      requests:
        memory: "2Gi"
        cpu: "1.5"
      limits:
        memory: "4Gi"
        cpu: "3"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: model-evaluation
  namespace: scheduler-benchmark
  labels:
    workload: ml-training-pipeline
    stage: evaluation
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/trained-model.h5,209715200,10,8,h5"
    data.scheduler.thesis/input-2: "intermediate/features.npz,15728640,5,7,npz"
    data.scheduler.thesis/output-1: "results/model-metrics.json,5242880,0,6,json"
    scheduler.thesis/compute-intensive: "true"
    scheduler.thesis/prefer-cloud: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: model-evaluator
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "model-evaluation"
    - name: WORKLOAD_ACTION
      value: "evaluate"
    - name: WORKLOAD_INTENSITY
      value: "high"
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: edge-inference-service
  namespace: scheduler-benchmark
  labels:
    workload: ml-training-pipeline
    stage: inference
  annotations:
    data.scheduler.thesis/input-1: "region1-bucket/trained-model.h5,209715200,3,9,h5"
    data.scheduler.thesis/input-2: "edge-data/inference-data.json,10485760,2,8,json"
    data.scheduler.thesis/output-1: "edge-data/predictions.json,5242880,0,7,json"
    scheduler.thesis/prefer-edge: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: inference-server
    image: davidandw190/workload-sim:latest
    command: [ "python", "/app/simulator.py" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: WORKLOAD_TYPE
      value: "inference"
    - name: WORKLOAD_ACTION
      value: "predict"
    - name: WORKLOAD_INTENSITY
      value: "medium"
    resources:
      requests:
        memory: "512Mi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "800m"
  restartPolicy: Never
