apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: data-locality-scheduler-rules
  namespace: monitoring
  labels:
    prometheus: prometheus-kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: data-locality.rules
    rules:
    # Data locality metrics
    - record: data_locality:local_data_percentage
      expr: local_data_access_percentage

    - record: data_locality:same_region_data_percentage
      expr: same_region_data_percentage

    - record: data_locality:cross_region_data_percentage
      expr: cross_region_data_percentage

    # Efficiency metrics
    - record: data_locality:scheduler_efficiency
      expr: 1 - (cross_region_data_percentage / 100)

    - record: data_locality:edge_utilization_ratio
      expr: avg(region_edge_utilization_ratio)

    # Node scoring averages
    - record: data_locality:avg_node_data_locality_score_by_type
      expr: avg(node_data_locality_score) by (node_type)

    - record: data_locality:avg_node_data_locality_score_by_region
      expr: avg(node_data_locality_score) by (region)

    # Resource efficiency
    - record: data_locality:avg_resource_efficiency
      expr: avg(resource_efficiency) by (resource_type)

    # Improvement metrics (for benchmarking)
    - record: data_locality:transfer_reduction_percentage
      expr: (data_locality:local_data_percentage + (data_locality:same_region_data_percentage * 0.8)) / 100

    # Data item locality
    - record: data_locality:total_data_items
      expr: sum(data_item_locality_count)

    - record: data_locality:local_data_items_percentage
      expr: data_item_locality_count{locality_type="local"} / data_locality:total_data_items * 100

    - record: data_locality:same_region_data_items_percentage
      expr: data_item_locality_count{locality_type="same_region"} / data_locality:total_data_items * 100

    - record: data_locality:cross_region_data_items_percentage
      expr: data_item_locality_count{locality_type="cross_region"} / data_locality:total_data_items * 100

    # Pod placement optimization
    - record: data_locality:pods_with_optimal_placement_percentage
      expr: sum(pod_locality_profile_count{profile="all_local"}) / sum(pod_locality_profile_count) * 100

    - record: data_locality:pods_with_suboptimal_placement_percentage
      expr: sum(pod_locality_profile_count{profile="no_local"}) / sum(pod_locality_profile_count) * 100
