prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: csi-cinder-sc-retain
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 30Gi

grafana:
  adminPassword: admin
  adminUser: admin
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: csi-cinder-sc-retain
  plugins:
  - grafana-piechart-panel
  - grafana-clock-panel
  - marcusolsson-json-datasource
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

alertmanager:
  enabled: true
