apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-locality-scheduler
  namespace: monitoring
  labels:
    prometheus: prometheus-kube-prometheus
    app: data-locality-scheduler
spec:
  selector:
    matchLabels:
      app: data-locality-scheduler
  namespaceSelector:
    matchNames:
    - data-locality-scheduler
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-locality-metrics
  namespace: monitoring
  labels:
    prometheus: prometheus-kube-prometheus
    app: data-locality-metrics
spec:
  selector:
    matchLabels:
      app: data-locality-metrics
  namespaceSelector:
    matchNames:
    - data-locality-scheduler
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
