apiVersion: v1
kind: ConfigMap
metadata:
  name: data-locality-scheduler-config
  namespace: data-locality-scheduler
data:
  scheduler-config.yaml: |
    # Basic settings
    schedulerName: "data-locality-scheduler"
    podQueueSize: 100
    healthServerPort: 8080
    refreshInterval: "5m"

    # Filtering options
    percentageOfNodesToScore: 50
    minFeasibleNodesToFind: 100

    # Bandwidth settings
    localBandwidth: 1000000000        # 1 GB/s
    sameZoneBandwidth: 500000000      # 500 MB/s
    sameRegionBandwidth: 200000000    # 200 MB/s
    crossRegionBandwidth: 50000000    # 50 MB/s
    edgeCloudBandwidth: 25000000      # 25 MB/s

    # Default weights
    resourceWeight: 0.3
    nodeAffinityWeight: 0.2
    nodeTypeWeight: 0.1
    capabilitiesWeight: 0.1
    dataLocalityWeight: 0.3

    # Data-intensive weights
    dataIntensiveResourceWeight: 0.2
    dataIntensiveNodeAffinityWeight: 0.1
    dataIntensiveNodeTypeWeight: 0.1
    dataIntensiveCapabilitiesWeight: 0.1
    dataIntensiveDataLocalityWeight: 0.6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-locality-scheduler
  namespace: data-locality-scheduler
  labels:
    app: data-locality-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-locality-scheduler
  template:
    metadata:
      labels:
        app: data-locality-scheduler
    spec:
      serviceAccountName: data-locality-scheduler
      containers:
      - name: scheduler
        image: davidandw190/data-locality-scheduler:latest
        imagePullPolicy: Always
        args:
        - "--config=/etc/scheduler/scheduler-config.yaml"
        - "--verbose=true"
        # - "ls -la /etc/scheduler && cat /etc/scheduler/scheduler-config.yaml && exec /app/data-locality-scheduler --config=/etc/scheduler/scheduler-config.yaml --verbose=true"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/scheduler
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: config-volume
        configMap:
          name: data-locality-scheduler-config
---
apiVersion: v1
kind: Service
metadata:
  name: data-locality-scheduler
  namespace: data-locality-scheduler
  annotations:
    description: "Service exposing health check and API endpoints for the scheduler"
spec:
  selector:
    app: data-locality-scheduler
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
