schedulerName: "data-locality-scheduler"
podQueueSize: 100
healthServerPort: 8080
# schedulerInterval: "1s"
refreshInterval: "5m"
enableMockData: false

# filtering options
percentageOfNodesToScore: 100
minFeasibleNodesToFind: 100
maxFailedAttempts: 5

resourceCacheEnabled: true
resourceCacheExpiration: "30s"
storageCacheExpiration: "5m"

resourceWeight: 0.1
nodeAffinityWeight: 0.1
nodeTypeWeight: 0.2
capabilitiesWeight: 0.1
dataLocalityWeight: 0.5

dataIntensiveResourceWeight: 0.05
dataIntensiveNodeAffinityWeight: 0.1
dataIntensiveNodeTypeWeight: 0.1
dataIntensiveCapabilitiesWeight: 0.1
dataIntensiveDataLocalityWeight: 0.65

computeIntensiveResourceWeight: 0.5
computeIntensiveNodeAffinityWeight: 0.2
computeIntensiveNodeTypeWeight: 0.1
computeIntensiveCapabilitiesWeight: 0.1
computeIntensiveDataLocalityWeight: 0.1

localBandwidth: 1000000000 # 1 GB/s
sameZoneBandwidth: 600000000 # 600 MB/s
sameRegionBandwidth: 200000000 # 200 MB/s
crossRegionBandwidth: 50000000 # 50 MB/s
edgeCloudBandwidth: 25000000 # 25 MB/s

localLatency: 0.1
sameZoneLatency: 1.0
sameRegionLatency: 5.0
crossRegionLatency: 30.0
edgeCloudLatency: 40.0

defaultCPURequest: 100 # 100m
defaultMemoryRequest: 209715200 # 200Mi

# node scoring options
minResourceScore: 0
maxResourceScore: 100
defaultScore: 50

# debug options
verboseLogging: true
detailedMetrics: true
enableProfiling: false
enableAPIEndpoint: true

metricsEndpoint: "/metrics"
metricsPort: 8080

metricsHistorySize: 100
