# Basic settings
schedulerName: "data-locality-scheduler"
podQueueSize: 100
healthServerPort: 8080
schedulerInterval: "1s"
refreshInterval: "5m"
enableMockData: false

# Filtering options
percentageOfNodesToScore: 100
minFeasibleNodesToFind: 100
maxFailedAttempts: 5

# Caching options
resourceCacheEnabled: true
resourceCacheExpiration: "30s"
storageCacheExpiration: "5m"

# Default weights
resourceWeight: 0.3
nodeAffinityWeight: 0.2
nodeTypeWeight: 0.1
capabilitiesWeight: 0.1
dataLocalityWeight: 0.3

# Data-intensive weights
dataIntensiveResourceWeight: 0.2
dataIntensiveNodeAffinityWeight: 0.1
dataIntensiveNodeTypeWeight: 0.1
dataIntensiveCapabilitiesWeight: 0.1
dataIntensiveDataLocalityWeight: 0.5

# Compute-intensive weights
computeIntensiveResourceWeight: 0.5
computeIntensiveNodeAffinityWeight: 0.2
computeIntensiveNodeTypeWeight: 0.1
computeIntensiveCapabilitiesWeight: 0.1
computeIntensiveDataLocalityWeight: 0.1

# Bandwidth settings in bytes/second
localBandwidth: 1000000000 # 1 GB/s
sameZoneBandwidth: 500000000 # 500 MB/s
sameRegionBandwidth: 200000000 # 200 MB/s
crossRegionBandwidth: 50000000 # 50 MB/s
edgeCloudBandwidth: 25000000 # 25 MB/s

# Latency settings in milliseconds
localLatency: 0.1
sameZoneLatency: 1.0
sameRegionLatency: 5.0
crossRegionLatency: 30.0
edgeCloudLatency: 40.0

# Resource allocation defaults
defaultCPURequest: 100 # 100m
defaultMemoryRequest: 209715200 # 200Mi

# Node scoring options
minResourceScore: 0
maxResourceScore: 100
defaultScore: 50

# Debug options
verboseLogging: false
detailedMetrics: false
enableProfiling: false
enableAPIEndpoint: true
