apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-edge-region2
  namespace: data-locality-scheduler
  labels:
    app: minio-edge
    region: region-2
spec:
  selector:
    matchLabels:
      app: minio-edge
      region: region-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-edge
        region: region-2
    spec:
      nodeSelector:
        topology.kubernetes.io/region: region-2
        node-capability/node-type: edge
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        ports:
        - containerPort: 9000
          name: api
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-edge-region2
  namespace: data-locality-scheduler
spec:
  selector:
    app: minio-edge
    region: region-2
  ports:
  - port: 9000
    targetPort: 9000
    name: api
