apiVersion: v1
kind: ConfigMap
metadata:
  name: data-test-configmap
  namespace: data-locality-scheduler
data:
  test-data.json: |
    {
      "name": "test-data",
      "size": 1048576,
      "metadata": { 
        "type": "test", 
        "created": "2025-03-22"
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: data-consumer-pod
  namespace: data-locality-scheduler
  annotations:
    data.scheduler.thesis/input-1: "test-bucket/test-data.json,1048576,5,3,json"
    data.scheduler.thesis/output-1: "results-bucket/result-data.json,2097152,0,4,json"
    scheduler.thesis/prefer-edge: "true"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: data-processor
    image: python:3.9
    command: [ "python", "-c", "import time, os; print(f'Processing data on {os.environ.get(\"NODE_NAME\", \"unknown\")}'); time.sleep(3600)" ]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - name: test-data
      mountPath: /data
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  volumes:
  - name: test-data
    configMap:
      name: data-test-configmap
  restartPolicy: Never
