apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-locality-metrics
  namespace: data-locality-scheduler
  labels:
    app: data-locality-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-locality-metrics
  template:
    metadata:
      labels:
        app: data-locality-metrics
    spec:
      serviceAccountName: data-locality-scheduler
      containers:
      - name: metrics-exporter
        image: davidandw190/data-locality-metrics:latest
        args:
        - "--scheduler-url=http://data-locality-scheduler.data-locality-scheduler.svc.cluster.local:8080"
        - "--metrics-interval=30s"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: LOG_LEVEL
          value: "debug"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: data-locality-metrics
  namespace: data-locality-scheduler
  labels:
    app: data-locality-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: data-locality-metrics
  ports:
  - port: 8080
    targetPort: 8080
    name: http
